name: lazy_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.0
  flutter_bloc: ^6.1.3
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter:

  uses-material-design: true
